ninety_nine_Cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :create, :new, :update, :edit]

end

ninety_nine_Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_Cats/app/models/cat.rb
require 'date'

class Cat < ApplicationRecord 
  include ActionView::Helpers::DateHelper

  COLORS = [
    'BLACK', 'WHITE', 'ORANGE', 'BROWN'
  ]


  validates :birth_date, presence: true
  validates :color, presence: true, inclusion: { in: COLORS }
  validates :name, presence: true
  validates :sex, presence: true, inclusion: { in: %w(M , F),
    message: "%{value} is not a valid sex" }
  validates :description, presence: true 

  has_many :rental_requests,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest

  def age
    b_day = self.birth_date
    time_ago_in_words(b_day)
  end


end 

ninety_nine_Cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  STATUSES = ['APPROVED', 'DENIED', 'PENDING']

  validates :status, presence: true, inclusion: { in: STATUSES  }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :cat_id, presence: true
  validate :overlapping_requests

  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat,
  dependent: :destroy


  

  def overlapping_requests
    cat_rentals = Cat.where(id: self.cat_id).includes(:rental_requests)
    cat_rentals = cat_rentals.first.rental_requests
    request = self
    cat_rentals.each do |rental|
      unless request.non_overlapping_requests(rental) 
        raise "This cat is booked these dates"
      end
    end
    true
  end

  def non_overlapping_requests(rental)
    if self.start_date > rental.end_date || rental.start_date > self.end_date
      return true
    end
    false
  end

end

ninety_nine_Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index 
    @cats = Cat.all 
    render :index 
  end 

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    kit = Cat.new(cat_params)
    if kit.save
      redirect_to cat_url(kit)
    else 
      render json: kit.errors.full_messages 
    end 
  end 

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages
    end
  end

  def new 
    @cat = Cat.new 
  end 

  private 
  
  def cat_params 
    params.require(:cat).permit(:name, :color, :sex, :description, :birth_date)
  end 
end 

ninety_nine_Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_Cats/app/views/cats/_form.html.erb
<h1><%= heading %></h1>



<form action="<%= actional %>" method="POST">
  <% if actional == cat_url(@cat) %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label for="name">Name:</label>
    <input type="text" id="name" name="cat[name]" value="<%= cat.name %>"><br>
  <br><label for="sex">Sex:</label><br>
    <% if cat.sex == "M" %>
      <input type="radio" name="cat[sex]" id="sex" value="M" checked>Male<br>
      <input type="radio" name="cat[sex]" id="sex" value="F">Female<br>
    <% else %>
      <input type="radio" name="cat[sex]" id="sex" value="M">Male<br>
      <input type="radio" name="cat[sex]" id="sex" value="F" checked>Female<br>
    <% end %>
  <br><label for="color">Color:</label>
    <select name="cat[color]" id="color" >
      <option value="BLANK">Please Select Color</option>
      <option value="BLACK" <%= "selected" if cat.color == "BLACK" %>>Black</option>
      <option value="BROWN" <%= "selected" if cat.color == "BROWN" %> >Brown</option>
      <option value="ORANGE" <%= "selected" if cat.color == "ORANGE" %>>Orange</option>
      <option value="WHITE" <%= "selected" if cat.color == "WHITE" %>>White</option>      
    </select><br>
  <br><label for="birth_date">Birthday:</label>
    <input type="date" name="cat[birth_date]" id="birth_date" value="<%= cat.birth_date %>" max="<%= Time.now %>"><br>
  <br><label for="description">Description:</label>
    <textarea type="text" name="cat[description]" id="description"><%= cat.description %></textarea> <br>
  <br><input type="submit" value="<%= submitter %> your cat">
</form>

ninety_nine_Cats/app/views/cats/edit.html.erb
<!-- <h1>Update your cat!</h1> -->

<%= render 'form', cat: @cat, actional: cat_url(@cat), submitter: "update", heading: "Update your cat!" %>

<!-- <form action="<%#= cat_url(@cat) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <label for="name">Name:</label>
    <input type="text" id="name" name="cat[name]" value="<%#= @cat.name %>"><br>
  <br><label for="sex">Sex:</label><br>
    <% if @cat.sex == "M" %>
      <input type="radio" name="cat[sex]" id="sex" value="M" checked>Male<br>
      <input type="radio" name="cat[sex]" id="sex" value="F">Female<br>
    <% else %>
      <input type="radio" name="cat[sex]" id="sex" value="M">Male<br>
      <input type="radio" name="cat[sex]" id="sex" value="F" checked>Female<br>
    <% end %>
  <br><label for="color">Color:</label>
    <select name="cat[color]" id="color" >
      <option value="BLANK">Please Select Color</option>
      <option value="BLACK" <%#= "selected" if @cat.color == "BLACK" %>>Black</option>
      <option value="BROWN" <%#= "selected" if @cat.color == "BROWN" %> >Brown</option>
      <option value="ORANGE" <%#= "selected" if @cat.color == "ORANGE" %>>Orange</option>
      <option value="WHITE" <%#= "selected" if @cat.color == "WHITE" %>>White</option>      
    </select><br>
  <br><label for="birth_date">Birthday:</label>
    <input type="date" name="cat[birth_date]" id="birth_date" value="<%#= @cat.birth_date %>" max="<%#= Time.now %>"><br>
  <br><label for="description">Description:</label>
    <textarea type="text" name="cat[description]" id="description"><%#= @cat.description %></textarea> <br>
  <br><input type="submit" value="Update Your Cat">
</form> -->

ninety_nine_Cats/app/views/cats/index.html.erb
<h1>All the Cats</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= cat.name %>
      <a href="<%= cat_url(cat) %>"> Show me this cat </a>
    </li>
  <% end %>
</ul>

ninety_nine_Cats/app/views/cats/new.html.erb
<!-- <h1>Create your cat!</h1> -->

<%= render 'form', cat: @cat, actional: cats_url, submitter: "create", heading: "Create your cat!" %>

<!-- <form action="<%#= cats_url %>" method="POST">
  <label for="name">Name:</label>
    <input type="text" id="name" name="cat[name]"><br>
  <br><label for="sex">Sex:</label><br>
    <input type="radio" name="cat[sex]" id="sex" value="M" checked>Male<br>
    <input type="radio" name="cat[sex]" id="sex" value="F">Female<br>
  <br><label for="color">Color:</label>
    <select name="cat[color]" id="color">
      <option value="BLANK">Please Select Color</option>
      <option value="BLACK">Black</option>
      <option value="BROWN">Brown</option>
      <option value="ORANGE">Orange</option>
      <option value="WHITE">White</option>      
    </select><br>
  <br><label for="birth_date">Birthday:</label>
    <input type="date" name="cat[birth_date]" id="birth_date" max="<%#= Time.now %>"><br>
  <br><label for="description">Description:</label>
    <textarea type="text" name="cat[description]" id="description"> </textarea> <br>
  <br><input type="submit" value="Make Your Cat">
</form> -->

ninety_nine_Cats/app/views/cats/show.html.erb
<h1>This is your cat:</h1>

<!-- <ul>
  <li>Name: <%#= @cat.name %></li>
  <li>Color: <%#= @cat.color %></li>
  <li>Age: <%#= @cat.age %></li>
  <li>Sex: <%#= @cat.sex %></li>
  <li>Description: <%#= @cat.description %></li>


</ul> -->

<table>
  <thead>
    <tr>
      <th colspan="3"><%= @cat.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Color:</td>
      <td>Age:</td>
      <td>Sex:</td>
    </tr>
    <tr>
      <td><%= @cat.color %></td>
      <td><%= @cat.age %></td>
      <td><%= @cat.sex %></td>
    </tr>
  </tbody>
</table>

<p>Description: <%= @cat.description %></p>

ninety_nine_Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>